export interface iProduct {
    name: string,
    baths: number,
    rooms: number,
    country: string,
    department: string,
    state: string,
    building_area: number,
    type: string,
    forSale: boolean,
    salePrice: number | null,
    forRent: boolean,
    rentPrice: number | null,
    socialStratum: string,
    age: string,
    code: string,
}

export interface iFilters {
    price: [string, string],
    stratum: string,
    age: string,
    building_area: [string, string],
    rooms: string,
    baths: string,
}

interface iTypeProperty {
    name: string,
    status: boolean
}

export let typeProperty: iTypeProperty[] = [
    { name: "Todos", status: true },
    { name: "Apartamento", status: false },
    { name: "Apartaestudio", status: false },
    { name: "Casa", status: false },
    { name: "Cabaña", status: false },
    { name: "Casa Campestre", status: false },
    { name: "Casa Lote", status: false },
    { name: "Finca", status: false },
    { name: "Habitación", status: false },
    { name: "Lote", status: false },
    { name: "Bodega", status: false },
    { name: "Consultorio", status: false },
    { name: "Local", status: false },
    { name: "Oficina", status: false },
    { name: "Parqueadero", status: false },
    { name: "Edificio", status: false },
]

export let Products: iProduct[] = [
    {
        name: "Propiedad 1",
        baths: 3,
        rooms: 4,
        country: "Estados Unidos",
        department: "California",
        state: "CA",
        building_area: 200,
        type: "Casa",
        forSale: true,
        salePrice: 450000,
        forRent: false,
        rentPrice: null,
        socialStratum: "3",
        age: "1",
        code: "ABC123",
    },
    {
        name: "Propiedad 2",
        baths: 2,
        rooms: 3,
        country: "España",
        department: "Andalucía",
        state: "Sevilla",
        building_area: 150,
        type: "Apartamento",
        forSale: true,
        salePrice: 300000,
        forRent: false,
        rentPrice: null,
        socialStratum: "2",
        age: "16",
        code: "XYZ456",
    },
    {
        name: "Propiedad 3",
        baths: 4,
        rooms: 5,
        country: "México",
        department: "Quintana Roo",
        state: "Cancún",
        building_area: 250,
        type: "Casa",
        forSale: false,
        salePrice: null,
        forRent: true,
        rentPrice: 2500,
        socialStratum: "4",
        age: "38",
        code: "LMN789",
    },
    {
        name: "Propiedad 4",
        baths: 1,
        rooms: 1,
        country: "Argentina",
        department: "Buenos Aires",
        state: "CABA",
        building_area: 70,
        type: "Departamento",
        forSale: true,
        salePrice: 150000,
        forRent: false,
        rentPrice: null,
        socialStratum: "1",
        age: "3",
        code: "PQR123",
    },
    {
        name: "Propiedad 5",
        baths: 2,
        rooms: 3,
        country: "Francia",
        department: "París",
        state: "Île-de-France",
        building_area: 120,
        type: "Apartamento",
        forSale: true,
        salePrice: 400000,
        forRent: false,
        rentPrice: null,
        socialStratum: "2",
        age: "6",
        code: "STU456",
    },
    {
        name: "Propiedad 6",
        baths: 2,
        rooms: 2,
        country: "Canadá",
        department: "Ontario",
        state: "ON",
        building_area: 100,
        type: "Condo",
        forSale: true,
        salePrice: 280000,
        forRent: true,
        rentPrice: 1600,
        socialStratum: "2",
        age: "3",
        code: "EFG789",
    },
    {
        name: "Propiedad 7",
        baths: 3,
        rooms: 4,
        country: "Australia",
        department: "Sídney",
        state: "NSW",
        building_area: 180,
        type: "Casa",
        forSale: true,
        salePrice: 550000,
        forRent: false,
        rentPrice: null,
        socialStratum: "3",
        age: "5",
        code: "HIJ123",
    },
    {
        name: "Propiedad 8",
        baths: 2,
        rooms: 2,
        country: "Italia",
        department: "Toscana",
        state: "Toscana",
        building_area: 160,
        type: "Villa",
        forSale: false,
        salePrice: null,
        forRent: true,
        rentPrice: 2200,
        socialStratum: "4",
        age: "7",
        code: "KLM456",
    },
    {
        name: "Propiedad 9",
        baths: 4,
        rooms: 5,
        country: "Reino Unido",
        department: "Londres",
        state: "Inglaterra",
        building_area: 220,
        type: "Townhouse",
        forSale: false,
        salePrice: null,
        forRent: true,
        rentPrice: 1800,
        socialStratum: "5",
        age: "10",
        code: "NOP789",
    },
    {
        name: "Propiedad 10",
        baths: 3,
        rooms: 4,
        country: "Alemania",
        department: "Berlín",
        state: "Berlín",
        building_area: 200,
        type: "Apartamento",
        forSale: true,
        salePrice: 600000,
        forRent: false,
        rentPrice: null,
        socialStratum: "4",
        age: "9",
        code: "QRS123",
    },
    {
        name: "Propiedad 11",
        baths: 1,
        rooms: 2,
        country: "Japón",
        department: "Tokio",
        state: "Kantō",
        building_area: 90,
        type: "Apartaestudio",
        forSale: true,
        salePrice: 200000,
        forRent: false,
        rentPrice: null,
        socialStratum: "3",
        age: "4",
        code: "TUV456",
    },
    {
        name: "Propiedad 12",
        baths: 2,
        rooms: 3,
        country: "Brasil",
        department: "Río de Janeiro",
        state: "RJ",
        building_area: 140,
        type: "Casa de Playa",
        forSale: true,
        salePrice: 200000,
        forRent: false,
        rentPrice: null,
        socialStratum: "3",
        age: "4",
        code: "TUV456",
    },
]
export const Stratum: string[] = ["Todos", "Campestre", "1", "2", "3", "4", "5", "6"]
export const Age: string[] = ["Todos", "1 A 8", "9 A 15", "16 A 30", "Más De 30"]
export const Rooms: string[] = ["1", "2", "3", "4+"]
export const Baths: string[] = ["1", "2", "3", "4+"]